# Generated by Django 5.1.3 on 2024-11-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
    ]
