# Generated by Django 5.1.3 on 2024-11-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_remove_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchesuploads',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
